package main

import (
	"flag"
	"fmt"
	"os"

	"jenkins-monitor/internal/adhoc"
	"jenkins-monitor/internal/analyze"
	"jenkins-monitor/internal/monitor"
	"jenkins-monitor/internal/utils"
)

func main() {

	if len(os.Args) < 2 {
		printUsage()
		return
	}

	switch os.Args[1] {
	case "monitor":
		monitorCmd := flag.NewFlagSet("monitor", flag.ContinueOnError)
		outputFile := monitorCmd.String("output", "/var/lib/jenkins-monitor/processes.csv", "Path to the output CSV file")
		monitorCmd.Usage = func() {
			fmt.Fprintf(os.Stderr, "Usage of %s monitor:\n", os.Args[0])
			fmt.Fprintf(os.Stderr, "  Monitors Jenkins processes and logs CPU/memory usage to a CSV file.\n")
			monitorCmd.PrintDefaults()
		}
		utils.SetupLogging()
		if err := monitorCmd.Parse(os.Args[2:]); err != nil {
			utils.Fatal(fmt.Sprintf("Error parsing monitor command flags: %v", err))
		}
		monitor.RunMonitor(*outputFile)
	case "analyze":
		analyzeCmd := flag.NewFlagSet("analyze", flag.ContinueOnError)
		inputFile := analyzeCmd.String("input", "/var/lib/jenkins-monitor/processes.csv", "Path to the input CSV file")
		analyzeCmd.Usage = func() {
			fmt.Fprintf(os.Stderr, "Usage of %s analyze:\n", os.Args[0])
			fmt.Fprintf(os.Stderr, "  Analyzes a CSV file generated by the monitor command to report peak CPU and memory usage.\n")
			analyzeCmd.PrintDefaults()
		}
		utils.SetupLogging()
		if err := analyzeCmd.Parse(os.Args[2:]); err != nil {
			utils.Fatal(fmt.Sprintf("Error parsing analyze command flags: %v", err))
		}
		analyze.RunAnalyzer(*inputFile)
	case "adhoc":
		adhocCmd := flag.NewFlagSet("adhoc", flag.ContinueOnError)
		adhocCmd.Usage = func() {
			fmt.Fprintf(os.Stderr, "Usage of %s adhoc:\n", os.Args[0])
			fmt.Fprintf(os.Stderr, "  Performs an immediate scan of running Jenkins processes and displays their CPU and memory usage.\n")
			adhocCmd.PrintDefaults()
		}
		utils.SetupLogging()
		if err := adhocCmd.Parse(os.Args[2:]); err != nil {
			utils.Fatal(fmt.Sprintf("Error parsing adhoc command flags: %v", err))
		}
		adhoc.RunAdhoc()
	default:
		printUsage()
	}
}

func printUsage() {
	fmt.Fprintf(os.Stderr, "Usage: %s <command> [arguments]\n", os.Args[0])
	fmt.Fprintf(os.Stderr, "\nCommands:\n")
	fmt.Fprintf(os.Stderr, "  monitor   Continuously monitors Jenkins processes and logs data to a CSV file.\n")
	fmt.Fprintf(os.Stderr, "  analyze   Analyzes a CSV file to report peak CPU and memory usage.\n")
	fmt.Fprintf(os.Stderr, "  adhoc     Performs an immediate scan of Jenkins processes.\n")
	fmt.Fprintf(os.Stderr, "\nUse \"%s <command> -h\" for more information about a command.\n", os.Args[0])
}
